version: "3.2"
services:
 db:
    container_name: fms_db
    build: ./mysql
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_DATABASE: fms
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - main
 app:
    container_name: fms_app
    build: 
      context: .
      args:
        #requirements: requirements/development.txt
        requirements: requirements.txt

    #environment:
    #  - DJANGO_SETTINGS_MODULE=fms.settings.development
    #  - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - db
 nginx:
    container_name: fms_web
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/fms/static
    ports:
      - "80:80"
    networks:
      - main
    depends_on:
      - app

networks:
  main:
